[build]
  base = "/"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]
  included_files = ["sql/**"]
  timeout = "30"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
